### ISSUE TITLE
Reproducing results from the paper

### ISSUE THREAD

**Issue by andreas-abel** [ithemal/Ithemal#50]
Could you please add instructions on how to reproduce the results in the paper, in particular Figure 2 and 3, and table 3?

**Comment by CharithYMendis** [comment]
You can use our throughput profiler located at https://github.com/ithemal/timing-harness to recreate the dataset. A validation dataset is located at https://github.com/ithemal/bhive, but it does not have basic blocks for which you need a redistributable license (e.g., SPEC benchmarks). You will need to collect and time those basic blocks independently.
