### ISSUE TITLE
Data Collection

### ISSUE THREAD

**Issue by andreas-abel** [ithemal/Ithemal#52]
The Readme currently says "This repo contains a preliminary version of our data collection infrastructure; we plan on releasing a more detailed description and infrastructure soon."

What are the current plans regarding this?

**Comment by CharithYMendis** [comment]
Have you tried using the tools provided within the data_collection folder?

**Comment by andreas-abel** [comment]
Is this the code that was used to obtain the results in the paper? The Readme in the data_collection  folder says "Due to inaccuracies in the timing measurements this method is not preferred and not used by Ithemal."

I would like to reproduce the results in the paper. Does the repository contain everything that is necessary to do so?

**Comment by CharithYMendis** [comment]
It is one way of collecting timing results, which is not preferred and is removed from the Ithemal repo. You can use the other ways.

**Comment by andreas-abel** [comment]
Thanks. Could you provide some instructions on how to reproduce the results in the paper?

**Comment by CharithYMendis** [comment]
The data collection tools allow you to generate static BBs from arbitrary binaries. Then you would need to time them. The timing tools are not open-sourced as of yet (under review). We can let you know once the timing tools are available for download.

**Comment by andreas-abel** [comment]
> The data collection tools allow you to generate static BBs from arbitrary binaries. 

Could you provide a complete list of the binaries (including their versions) you used for the paper? Table 2 in the paper does not provide all the details necessary for reproducing the results.

Or would it be possible to provide the complete set of basic blocks that you used for the paper?

> The timing tools are not open-sourced as of yet (under review). We can let you know once the timing tools are available for download.

Could you give an estimate of how long this will take?

**Comment by CharithYMendis** [comment]
Except for SPEC2006, SPEC2017 and other proprietary binaries that we have in our dataset, we will be releasing the BBs of opensource programs soon. It will be released together with the timing tool. I cannot guarantee a timeline since the work is under review.

**Comment by CharithYMendis** [comment]
Be in touch, we will notify once we can release the dataset and the timing tool.

**Comment by andreas-abel** [comment]
> I cannot guarantee a timeline since the work is under review.

Could you make a rough guess regarding the timeline? Is it more likely, e.g., a couple of days, several weeks, or a few months?

**Comment by CharithYMendis** [comment]
> Could you make a rough guess regarding the timeline? Is it more likely, e.g., a couple of days, several weeks, or a few months?

It depends on the review process, please subscribe and we will let you know. Till then you can collect the basic blocks from SPEC 2006, SPEC 2017 and then when the dataset of open-sourced programs are available you can merge to create the full dataset.

**Comment by CharithYMendis** [comment]
Open a new issue, if you have trouble running the static basic block collection tools.
