### ISSUE TITLE
How Do I run run_ithemal.py

### ISSUE THREAD

**Issue by sjensenUT** [ithemal/Ithemal#56]
the wiki and the readme in ithemal/learning/pytorch/ithemal both present a different set of input arguments for running run_ithemal.py. However neither of these seem to be consistent with the set of input arguments that I can see by looking in run_ithemal.py
How can I run run_ithemal.py?
What set of arguments do I need? 
where are the necessary input files contained in your project?

**Comment by alexrenda** [comment]
Sorry -- that README in `ithemal/learning/pytorch/ithemal` was out of date, and shouldn't have been there. I've deleted it. The correct arguments are those at the top level of the repo:

`python learning/pytorch/ithemal/run_ithemal.py --data {DATA_FILE} --use-rnn train --experiment-name {EXPERIMENT_NAME} --experiment-time {EXPERIMENT_TIME} --sgd --threads 4 --trainers 6 --weird-lr --decay-lr --epochs 100`

- `DATA_FILE` is a torch.save file (which is pickle + torch metadata) containing a dataset as described here: https://github.com/ithemal/Ithemal#representation. You'll probably want to get these from bhive, unless you have some of your own code blocks you've timed.
- `EXPERIMENT_NAME` and `EXPERIMENT_TIME` are just names for storing the result, where `EXPERIMENT_TIME` is normally something like the output of `python -c 'import time,datetime; print(datetime.datetime.fromtimestamp(time.time()).isoformat())'`



For instance, training and testing Ithemal on some timings of ffmpeg from the current bhive repo:

```
cd "${ITHEMAL_HOME}"
EXPERIMENT_NAME="test-experiment"
EXPERIMENT_TIME="$(python -c 'import time,datetime; print(datetime.datetime.fromtimestamp(time.time()).isoformat())')"
DATA_FILE="ffmpeg.pkl"
NUM_TRAINERS="1" # to actually train, we used 6, but 1 is better to make sure that it all works
wget https://github.com/ithemal/bhive/raw/cd5f9db/sources/ffmpeg.csv # get the code strings
wget https://github.com/ithemal/bhive/raw/cd5f9db/throughput/hsw.csv # get the HSW timings
python -c "import subprocess, torch; hsw = {k: float(v) for (k, v) in map(lambda x: x.split(','), open('hsw.csv').readlines())}; l = [(i, hsw[l], None, subprocess.check_output(['data_collection/build/bin/tokenizer', l.split(',')[0], '--token'], universal_newlines=True).strip()) for i, (l, _) in enumerate(map(lambda x: x.split(','), open('ffmpeg.csv').readlines())) if l in hsw]; torch.save(l, '${DATA_FILE}')"
python learning/pytorch/ithemal/run_ithemal.py --data ${DATA_FILE} --use-rnn train --experiment-name ${EXPERIMENT_NAME} --experiment-time ${EXPERIMENT_TIME} --sgd --threads 4 --trainers ${NUM_TRAINERS} --weird-lr --decay-lr --epochs 100
```

Let me know if you have any issues!

**Comment by sjensenUT** [comment]
Hello Alex, Thanks for the response.
I've been playing around with this for the last few days.
Unfortunately, when I run the above example, I get the following runtime error message

Traceback (most recent call last):
  File "learning/pytorch/ithemal/run_ithemal.py", line 279, in <module>
    main()
  File "learning/pytorch/ithemal/run_ithemal.py", line 257, in main
    training.run_training_coordinator(base_params, train_params)
  File "/home/ithemal/ithemal/learning/pytorch/ithemal/training.py", line 366, in run_training_coordinator
    loss_reporter.finish()
  File "/home/ithemal/ithemal/learning/pytorch/ithemal/training.py", line 162, in finish
    self.trainer.validate(resultfile)
  File "/home/ithemal/ithemal/learning/pytorch/models/train.py", line 339, in validate
    output = self.model(item)
  File "/opt/conda/envs/ithemal/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ithemal/ithemal/learning/pytorch/models/graph_models.py", line 458, in forward
    instr_chain = torch.stack([token_output_map[instr][-1] for instr in item.block.instrs])
I looked a bit into what might be causing this error, and I found that immediately before the error is created, in the train.py script the length of item.x in train.py/validate is 0.
I would assume that's what is causing this  error.
Do you know how to fix it?
Thanks for your help

**Comment by alexrenda** [comment]
Does

**Comment by alexrenda** [comment]
Does
`python -c "import torch; torch.save([x for x in torch.load('${DATA_FILE}') if len(x[-1]) > 20], '${DATA_FILE}')"`
fix this for you?  It seems like there is an empty block in there (`(17149, 0.0, None, '<block></block>')`), and this should filter that out.

**Comment by sjensenUT** [comment]
Hey Thanks, that helped.
Everything seems to be working now.
