### ISSUE TITLE
Build gets stuck

### ISSUE THREAD

**Issue by IlonaAT** [ithemal/Ithemal#58]
Hello,

My purpose is to be able to reproduce your work to be able to eventually build on it to be able to make more predictions on performance with software.

After installing docker (with docker repositories) and docker compose, apparently without issues (Ubuntu 20), and after extracting the zip of Ithemas repo, I try to build it (docker/docker_build.sh) and it gets stuck at step 8/26 Solving environment: ...working... 

After I few hours I kill it....

You have any clue why this is happening? How long should the build take approximately?

Thanks, Ilona

**Comment by alexrenda** [comment]
Seems to be happening because some aspect of conda changed again (similar to #49).

Does the change in the issue-58 branch (ithemal/Ithemal@3a9ac27) fix this for you?

**Comment by IlonaAT** [comment]
The build worked, so let's tackle the next steps. :)
Thanks Alex, sorry I did not see this before.
