### ISSUE TITLE
Mapping Immediate Values to CONSTANT Token

### ISSUE THREAD

**Issue by mostafaelhoushi** [ithemal/Ithemal#62]
Hello
Quoting from the paper:
![image](https://user-images.githubusercontent.com/1451293/99405249-8f694100-28ba-11eb-81e5-2931d448b420.png)

It seems that immediate operands of instructions are mapped to a `CONSTANT` token. However, looking at the code, especially in `data_cost.py` I don't see this conversion happening.

Can you point us to where it is happening in the code?

**Comment by alexrenda** [comment]
The conversion happens before it gets into the Python code — specifically, in this series of if-else blocks: https://github.com/ithemal/Ithemal/blob/cb679b576d1ea6c447b1a0896a9cbffa273b2c98/data_collection/common/code_embedding.c#L399

**Comment by mostafaelhoushi** [comment]
Thanks @alexrenda for your quick response! I highly appreciate that.
