### ISSUE TITLE
Data collection

### ISSUE THREAD

**Issue by anilavakundu** [ithemal/Ithemal#64]
Is there a detailed README on how to collect data replicating all the assumptions mentioned in the paper? 

I am unable to make sense of the scripts provided in `data_collection` 

Thanks!

**Comment by alexrenda** [comment]
The scripts in `data_collection` are deprecated. The best way to collect data with assumptions in the paper is to use the BHive basic block profiler scripts available at https://github.com/ithemal/bhive
